apiVersion: v1
kind: Service
metadata:
  name: kubeservice
spec:
  selector:
    app: coderusers
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coderusers
spec:
  replicas: 5
  selector:
    matchLabels:
      app: coderusers
  template:
    metadata:
      labels:
        app: coderusers
    spec:
      containers:
        - name: kubecontainer
          image: fergiraudo91/userscreator:1.0.0
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_URL
              value: mongodb+srv://fergiraudo91:Luna.2024@coder.3hytpje.mongodb.net/coder
          imagePullPolicy: Always